name: jhartley-one
version: '0.7'
summary: My swizzy test snap
description: |
  Jonathan Hartley's test app,
  now with pazazz.

base: core18
confinement: strict
grade: stable

parts:
  jhartley-one:
    plugin: python
    python-version: python3
    source: .
    stage-packages: []

apps:
  jhartley-one:
    command: bin/jhartley-one

