name: jhartley-one
version: '0.2'
summary: My test snap.
description: |
  Jonathan Hartley's test app,
  that does all the things.

base: core18
confinement: strict

parts:
  jhartley-one:
    plugin: python
    python-version: python3
    source: .
    stage-packages: []

apps:
  jhartley-one:
    command: bin/jhartley-one

